version = 0.1
[default.deploy.parameters]
stack_name = "tf-cloud-destroy-lambda"
resolve_s3 = true
s3_prefix = "tf-cloud-destroy-lambda"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
